AddCSLuaFile()

language.Add( "g64_mario", "Mario" )

language.Add( "tool.g64surfacechanger.name", "Surface Changer" )
language.Add( "tool.g64surfacechanger.desc", "Change the G64 surface of an object" )
language.Add( "tool.g64surfacechanger.surf", "Surface type" )
language.Add( "tool.g64surfacechanger.terr", "Terrain type" )
language.Add( "tool.g64surfacechanger.left", "Apply selected Surface / Terrain Type to an object" )

language.Add( "tool.g64surfacechanger.stone", "Stone" )
language.Add( "tool.g64surfacechanger.grass", "Grass" )
language.Add( "tool.g64surfacechanger.snow", "Snow" )
language.Add( "tool.g64surfacechanger.sand", "Sand" )
language.Add( "tool.g64surfacechanger.spooky", "Spooky" )
language.Add( "tool.g64surfacechanger.water", "Water" )
language.Add( "tool.g64surfacechanger.slide", "Slide" )

language.Add( "tool.g64surfacechanger.default", "Default" )
language.Add( "tool.g64surfacechanger.burning", "Burning" )
language.Add( "tool.g64surfacechanger.hangable", "Hangable" )
language.Add( "tool.g64surfacechanger.slow", "Slow" )
language.Add( "tool.g64surfacechanger.very_slippery", "Very Slippery" )
language.Add( "tool.g64surfacechanger.slippery", "Slippery" )
language.Add( "tool.g64surfacechanger.not_slippery", "Not Slippery" )
language.Add( "tool.g64surfacechanger.shallow_quicksand", "Shallow Quicksand" )
language.Add( "tool.g64surfacechanger.deep_quicksand", "Deep Quicksand" )
language.Add( "tool.g64surfacechanger.instant_quicksand", "Instant Quicksand" )
language.Add( "tool.g64surfacechanger.ice", "Ice" )
language.Add( "tool.g64surfacechanger.hard", "Hard" )
language.Add( "tool.g64surfacechanger.hard_slippery", "Hard Slippery" )
language.Add( "tool.g64surfacechanger.hard_very_slippery", "Hard Very Slippery" )
language.Add( "tool.g64surfacechanger.hard_not_slippery", "Hard Not Slippery" )
language.Add( "tool.g64surfacechanger.vertical_wind", "Vertical Wind" )
language.Add( "tool.g64surfacechanger.horizontal_wind", "Horizontal Wind" )
language.Add( "tool.g64surfacechanger.quicksand", "Quicksand" )
language.Add( "tool.g64surfacechanger.noise_default", "Noise Default" )